apiVersion: v1
kind: ConfigMap
metadata:
  name: nem-scheduler-config
  namespace: nem
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: "http://+:5600"
  ConnectionStrings__SchedulerDb: "Host=postgres;Port=5432;Database=nemscheduler;Username=nemscheduler;Password=nemscheduler_dev"
  Mimir__BaseUrl: "http://nem-mimir:5223"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  NEM_CONFIGURATION_URL: "http://nem-configuration:8080"
