apiVersion: apps/v1
kind: Deployment
metadata:
  name: nem-scheduler
  namespace: nem
  labels:
    app: nem-scheduler
    app.kubernetes.io/part-of: nem-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nem-scheduler
  template:
    metadata:
      labels:
        app: nem-scheduler
        app.kubernetes.io/part-of: nem-platform
    spec:
      containers:
        - name: nem-scheduler
          image: localhost:5000/nem-scheduler:dev
          ports:
            - containerPort: 5600
          envFrom:
            - configMapRef:
                name: nem-scheduler-config
          env:
            - name: NemConfiguration__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: nem-scheduler-secret
                  key: NemConfiguration__ClientSecret
          startupProbe:
            httpGet:
              path: /health/ready
              port: 5600
            failureThreshold: 24
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5600
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5600
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
