apiVersion: v1
kind: Service
metadata:
  name: nem-scheduler
  namespace: nem
spec:
  type: ClusterIP
  selector:
    app: nem-scheduler
  ports:
    - port: 5600
      targetPort: 5600
      protocol: TCP
