apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nem-comms-data-protection
  namespace: nem-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
