apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nem-comms-configuration-secret
  namespace: nem-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: nem-comms-configuration-secret
  data:
    - remoteRef:
        key: secret/data/services/comms
        property: configuration-client-secret
      secretKey: NemConfiguration__ClientSecret
    - remoteRef:
        key: secret/data/services/comms/data-protection
        property: certificate
      secretKey: tls.crt
    - remoteRef:
        key: secret/data/services/comms/data-protection
        property: private-key
      secretKey: tls.key
