apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-data

resources:
  - namespace.yaml
  - ../../../base/infrastructure/opa

patches:
  - path: patch-nodeselector.yaml
    target:
      kind: Deployment
      name: opa
