apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: nem
  labels:
    app: loki
    app.kubernetes.io/part-of: nem-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
