apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-collector-storage
  namespace: nem
  labels:
    app: otel-collector
    app.kubernetes.io/part-of: nem-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
