apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: nem
  labels:
    app: otel-collector
    app.kubernetes.io/part-of: nem-platform
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
    - name: http-otlp
      port: 4318
      targetPort: 4318
    - name: health
      port: 13133
      targetPort: 13133
    - name: prometheus
      port: 8889
      targetPort: 8889
