apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nem-mimir-configuration-secret
  namespace: nem-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: nem-mimir-configuration-secret
  data:
    - remoteRef:
        key: secret/data/services/mimir
        property: configuration-client-secret
      secretKey: NemConfiguration__ClientSecret
