apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configuration-external-secret.yaml
  - configuration-token-egress-policy.yaml
  - configuration-service-egress-policy.yaml
