apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    app: grafana
    app.kubernetes.io/part-of: nem-platform
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: nem-federation
        orgId: 1
        folder: NEM Federation
        type: file
        disableDeletion: true
        allowUiUpdates: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        uid: prometheus
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - name: traceID
              datasourceUid: tempo
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        uid: tempo
        editable: false
        jsonData:
          nodeGraph:
            enabled: true
