apiVersion: v1
kind: Service
metadata:
  name: nem-classification
  namespace: nem
  labels:
    app: nem-classification
    app.kubernetes.io/part-of: nem-platform
spec:
  type: ClusterIP
  selector:
    app: nem-classification
  ports:
    - port: 5300
      targetPort: 5270
      protocol: TCP
