apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-policy
  namespace: nem
  labels:
    app: openbao
    app.kubernetes.io/part-of: nem-platform
data:
  nem-policy.hcl: |
    path "secret/data/nem/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
    path "secret/metadata/nem/*" {
      capabilities = ["list", "read", "delete"]
    }
