apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
    app.kubernetes.io/part-of: nem-platform
data:
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
      - name: Loki
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        uid: prometheus
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - name: traceID
              datasourceUid: tempo

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        uid: loki
        editable: false
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"traceId":"(\w+)"'
              name: TraceID
              url: '$${__value.raw}'

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        uid: tempo
        editable: false
        jsonData:
          tracesToLogs:
            datasourceUid: loki
            filterByTraceID: true
            filterBySpanID: true
          tracesToMetrics:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          serviceMap:
            datasourceUid: prometheus
