apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: nem
  labels:
    app: rabbitmq
    app.kubernetes.io/part-of: nem-platform
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: amqp
    name: amqp
  - port: 15672
    targetPort: management
    name: management
  - port: 15692
    targetPort: prometheus
    name: prometheus
