apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: nem
  labels:
    app: tempo
    app.kubernetes.io/part-of: nem-platform
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3200
    targetPort: 3200
    protocol: TCP
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
    protocol: TCP
  selector:
    app: tempo
