apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nem-inferencegateway-connection-secrets
  namespace: nem-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: nem-inferencegateway-connection-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        ConnectionStrings__DefaultConnection: "{{ .databaseConnectionString }};Maximum Pool Size=8;Minimum Pool Size=0;Connection Idle Lifetime=60"
        RabbitMq__ConnectionString: "{{ .rabbitMqConnectionString }}"
  data:
    - secretKey: databaseConnectionString
      remoteRef:
        key: secret/data/services/inferencegateway
        property: connection-string
    - secretKey: rabbitMqConnectionString
      remoteRef:
        key: secret/data/services/inferencegateway
        property: rabbitmq-connection-string
