apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nem

resources:
  - namespace.yaml
  - infrastructure/postgres
  - infrastructure/rabbitmq
  - infrastructure/keycloak
  - infrastructure/openbao
  - infrastructure/grafana
  - infrastructure/prometheus
  - infrastructure/loki
  - infrastructure/tempo
  - infrastructure/otel-collector
  - infrastructure/pgadmin
  - infrastructure/gateway
  - infrastructure/opa
  - infrastructure/registry
  - services/mcp
  - services/knowhub
  - services/mimir
  - services/classification
  - services/comms
  - services/backup
  - services/scheduler
  - services/mediahub
  - services/web
  - services/homeassistant
  - services/configuration
