apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: nem
  labels:
    app: keycloak
    app.kubernetes.io/part-of: nem-platform
type: Opaque
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: YWRtaW4=
  KC_BOOTSTRAP_ADMIN_PASSWORD: YWRtaW4=
