apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: nem
  labels:
    app: keycloak
    app.kubernetes.io/part-of: nem-platform
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
