apiVersion: apps/v1
kind: Deployment
metadata:
  name: nem-web-comms
  namespace: nem-apps
spec:
  template:
    spec:
      containers:
        - name: nem-web-comms
          env:
            - name: APP_URL
              value: https://nem.endorff.net
            - name: KEYCLOAK_PUBLIC_URL
              value: https://nem.endorff.net:8448/auth
            - name: KEYCLOAK_REALM
              value: nem
            - name: KEYCLOAK_CLIENT_ID
              value: nem-web
